name: Synchronize to forked repo

on:
  push: # 브랜치로 push될 때 실행
    branches:
      - main
      - develop
  pull_request: # PR 생성 및 업데이트 시 실행
    branches:
      - main # main 브랜치에 대한 PR
      - develop # develop 브랜치에 대한 PR

jobs:
  sync:
    name: Sync forked repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          cd Lotte-Cinema
          yarn install

      - name: Build project
        run: |
          cd Lotte-Cinema
          yarn run build

      - name: Add remote-url
        run: |
          git remote add forked-repo https://gonn-i:${{ secrets.FORKED_REPO_TOKEN }}@github.com/gonn-i/35-COLLABORATION-WEB-LOTTE_CINEMA
          git config user.name gonn-i
          git config user.email rlarhdms6828@naver.com

      - name: Push changes to forked-repo
        run: |
          git push -f forked-repo main

      - name: Clean up
        run: |
          git remote remove forked-repo
