name: Synchronize to forked repo

on:
  push: # 브랜치로 push될 때 실행
    branches:
      - main
  pull_request:
    branches:
      - develop

jobs:
  sync_push:
    name: Sync forked repo
    runs-on: ubuntu-latest

    if: github.event_name == 'push'
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.AUTO_SYNC}}

      - name: Install dependencies
        run: |
          cd Lotte-Cinema
          yarn install

      - name: Build project
        run: |
          cd Lotte-Cinema
          yarn run build

      - name: Add remote-url
        run: |
          git remote add forked-repo https://gonn-i:${{ secrets.AUTO_SYNC }}@github.com/gonn-i/35-COLLABORATION-WEB-LOTTE_CINEMA
          git config user.name gonn-i
          git config user.email rlarhdms6828@naver.com

      - name: Push changes to forked-repo
        run: |
          git push -f forked-repo HEAD:main

  sync_pr:
    name: Build project on pull_request
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout develop
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.AUTO_SYNC }}

      - name: Install dependencies
        run: |
          cd Lotte-Cinema
          yarn install

      - name: Build project
        run: |
          cd Lotte-Cinema
          yarn run build
